services:
  starter:
    ports:
      - "4005:4005"
    build:
      dockerfile: ./Dockerfile.dev
    environment:
      PAD_NOTES_DIR: /tmp/pad
    volumes:
      - ./:/app
      - /app/tmp
      - ./tmp/pad:/tmp/pad
    networks:
      - net

networks:
  net:
    driver: bridge
