version: '3'

tasks:
  default:
    desc: 'clean the project, generate templ files and the build the pcf binary'
    cmds:
      - task: build

  build:
    desc: 'generate templ files and the build the pcf binary'
    deps: [js, tailwind, templ]
    cmds:
      - go build -o ./tmp/pad ./main.go

  js:
    desc: 'run bun javascript bundler'
    cmds:
      - "bun run js"

  tailwind:
    desc: 'run tailwind transpiler'
    cmds:
      - "bun run tw"

  templ:
    desc: 'generate templ files'
    cmds:
      - templ generate ./ui/... 

  serve:
    desc: 'build then serve the project'
    cmds:
      - task: build
      - './starter serve'

  reverse:
    desc: 'test on android by forwarding the ports'
    cmds:
      - adb reverse tcp:4000 tcp:4000

  docker-build:
    desc: 'build production docker image'
    cmds:
      - docker build -t pad:latest -t pad:{{.TAG}} .
    vars:
      TAG:
        sh: git rev-parse --short HEAD

  docker-push:
    desc: 'build and push production docker image to registry'
    cmds:
      - task: docker-build
      - docker tag pad:latest {{.REGISTRY}}/pad:latest
      - docker tag pad:{{.TAG}} {{.REGISTRY}}/pad:{{.TAG}}
      - docker push {{.REGISTRY}}/pad:latest
      - docker push {{.REGISTRY}}/pad:{{.TAG}}
    vars:
      TAG:
        sh: git rev-parse --short HEAD
      REGISTRY: '{{.REGISTRY | default "ghcr.io/nanvenomous"}}'

  docker-run:
    desc: 'run production docker image locally'
    cmds:
      - docker run -p 4000:4000 -v ./pad:/data/notes pad:latest

